/**
 * generate-weekly.js
 *
 * Fetches all GitHub Releases tagged `daily-*` created in the past 7 days,
 * aggregates their content, sends to Claude API with the weekly marketing prompt,
 * and posts the result to Slack.
 *
 * Environment variables required:
 *   GITHUB_TOKEN            - GitHub token (provided by Actions)
 *   GITHUB_REPOSITORY       - "owner/repo" (provided by Actions)
 *   ANTHROPIC_API_KEY       - Claude API key
 *   SLACK_WEBHOOK_RELEASES  - Slack incoming webhook URL
 */

import { Octokit } from '@octokit/rest';
import { IncomingWebhook } from '@slack/webhook';
import Anthropic from '@anthropic-ai/sdk';
import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

async function getDailyReleasesForPeriod(days = 7) {
  const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
  const releases = [];
  let page = 1;

  while (true) {
    const { data } = await octokit.repos.listReleases({ owner, repo, per_page: 100, page });
    if (data.length === 0) break;

    for (const r of data) {
      if (!r.tag_name.startsWith('daily-')) continue;
      const publishedAt = new Date(r.published_at);
      if (publishedAt < since) break; // releases are sorted newest first
      releases.push(r);
    }

    // If the last release on this page is older than our window, stop paging
    if (data.length < 100) break;
    const lastDate = new Date(data[data.length - 1].published_at);
    if (lastDate < since) break;

    page++;
  }

  return releases;
}

async function callClaude(systemPrompt, userContent) {
  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  const message = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 1024,
    system: systemPrompt,
    messages: [{ role: 'user', content: userContent }],
  });
  return message.content[0].text;
}

async function main() {
  const releases = await getDailyReleasesForPeriod(7);
  console.log(`Found ${releases.length} daily releases in the past 7 days`);

  if (releases.length === 0) {
    console.log('No daily releases found this week. Skipping.');
    process.exit(0);
  }

  const aggregated = releases
    .sort((a, b) => new Date(a.published_at) - new Date(b.published_at))
    .map(r => `## ${r.name}\n\n${r.body}`)
    .join('\n\n---\n\n');

  const weekEnding = new Date().toISOString().split('T')[0];

  // Load prompt
  const promptPath = join(__dirname, '../../prompts/weekly-marketing.md');
  let systemPrompt;
  try {
    systemPrompt = readFileSync(promptPath, 'utf-8');
  } catch {
    systemPrompt = readFileSync(join(__dirname, '../../../prompts/weekly-marketing.md'), 'utf-8');
  }

  let summary;
  if (!process.env.ANTHROPIC_API_KEY) {
    console.warn('ANTHROPIC_API_KEY not set — using raw aggregated notes as summary');
    summary = aggregated;
  } else {
    console.log('Calling Claude API for weekly summary...');
    summary = await callClaude(
      systemPrompt,
      `Week ending ${weekEnding}\n\nDaily release notes:\n\n${aggregated}`
    );
    console.log('Weekly summary:\n', summary);
  }

  // Post to Slack
  if (process.env.SLACK_WEBHOOK_RELEASES) {
    const webhook = new IncomingWebhook(process.env.SLACK_WEBHOOK_RELEASES);
    await webhook.send({
      blocks: [
        {
          type: 'header',
          text: { type: 'plain_text', text: `Weekly Product Update — ${weekEnding}` },
        },
        {
          type: 'section',
          text: { type: 'mrkdwn', text: summary },
        },
        {
          type: 'context',
          elements: [
            { type: 'mrkdwn', text: `Based on ${releases.length} daily release${releases.length !== 1 ? 's' : ''} | Generated by Claude` },
          ],
        },
      ],
    });
    console.log('Posted weekly summary to Slack');
  } else {
    console.warn('SLACK_WEBHOOK_RELEASES not set — skipping Slack');
  }

  console.log('Weekly workflow complete.');
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
